server:
  port: 9091
grpc:
  client:
    auth:
      address: "localhost:9090"
      negotiationType: plaintext
    weather:
      address: "localhost:9093"
      negotiationType: plaintext
    promocodes:
      address: "localhost:9094"
      negotiationType: plaintext
