/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db.tables


import java.time.LocalDate
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.kimp.earnactive.db.Public
import org.kimp.earnactive.db.keys.PROMOCODES_PKEY
import org.kimp.earnactive.db.tables.records.PromocodesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Promocodes(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PromocodesRecord>?,
    aliased: Table<PromocodesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PromocodesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.promocodes</code>
         */
        val PROMOCODES: Promocodes = Promocodes()
    }

    /**
     * The class holding records for this type
     */
    public override fun getRecordType(): Class<PromocodesRecord> = PromocodesRecord::class.java

    /**
     * The column <code>public.promocodes.uuid</code>.
     */
    val UUID: TableField<PromocodesRecord, java.util.UUID?> = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.promocodes.name</code>.
     */
    val NAME: TableField<PromocodesRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.promocodes.description</code>.
     */
    val DESCRIPTION: TableField<PromocodesRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(1024).nullable(false), this, "")

    /**
     * The column <code>public.promocodes.value</code>.
     */
    val VALUE: TableField<PromocodesRecord, String?> = createField(DSL.name("value"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.promocodes.general_count</code>.
     */
    val GENERAL_COUNT: TableField<PromocodesRecord, Int?> = createField(DSL.name("general_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.promocodes.available_count</code>.
     */
    val AVAILABLE_COUNT: TableField<PromocodesRecord, Int?> = createField(DSL.name("available_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.promocodes.expiration_date</code>.
     */
    val EXPIRATION_DATE: TableField<PromocodesRecord, LocalDate?> = createField(DSL.name("expiration_date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("'2023-11-26'::date"), SQLDataType.LOCALDATE)), this, "")

    /**
     * The column <code>public.promocodes.cost</code>.
     */
    val COST: TableField<PromocodesRecord, Int?> = createField(DSL.name("cost"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PromocodesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PromocodesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.promocodes</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.promocodes</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.promocodes</code> table reference
     */
    constructor(): this(DSL.name("promocodes"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PromocodesRecord>): this(Internal.createPathAlias(child, key), child, key, PROMOCODES, null)
    public override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    public override fun getPrimaryKey(): UniqueKey<PromocodesRecord> = PROMOCODES_PKEY
    public override fun `as`(alias: String): Promocodes = Promocodes(DSL.name(alias), this)
    public override fun `as`(alias: Name): Promocodes = Promocodes(alias, this)
    public override fun `as`(alias: Table<*>): Promocodes = Promocodes(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    public override fun rename(name: String): Promocodes = Promocodes(DSL.name(name), null)

    /**
     * Rename this table
     */
    public override fun rename(name: Name): Promocodes = Promocodes(name, null)

    /**
     * Rename this table
     */
    public override fun rename(name: Table<*>): Promocodes = Promocodes(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    public override fun fieldsRow(): Row8<java.util.UUID?, String?, String?, String?, Int?, Int?, LocalDate?, Int?> = super.fieldsRow() as Row8<java.util.UUID?, String?, String?, String?, Int?, Int?, LocalDate?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (java.util.UUID?, String?, String?, String?, Int?, Int?, LocalDate?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (java.util.UUID?, String?, String?, String?, Int?, Int?, LocalDate?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
