/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db.tables


import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.kimp.earnactive.db.Public
import org.kimp.earnactive.db.keys.USERS_PROMOCODES__FK_PROMOCODE_USER
import org.kimp.earnactive.db.keys.USERS_PROMOCODES__FK_USER_PROMOCODE
import org.kimp.earnactive.db.tables.records.UsersPromocodesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersPromocodes(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UsersPromocodesRecord>?,
    aliased: Table<UsersPromocodesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UsersPromocodesRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.users_promocodes</code>
         */
        val USERS_PROMOCODES: UsersPromocodes = UsersPromocodes()
    }

    /**
     * The class holding records for this type
     */
    public override fun getRecordType(): Class<UsersPromocodesRecord> = UsersPromocodesRecord::class.java

    /**
     * The column <code>public.users_promocodes.user_uuid</code>.
     */
    val USER_UUID: TableField<UsersPromocodesRecord, UUID?> = createField(DSL.name("user_uuid"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.users_promocodes.promocode_uuid</code>.
     */
    val PROMOCODE_UUID: TableField<UsersPromocodesRecord, UUID?> = createField(DSL.name("promocode_uuid"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.users_promocodes.is_used</code>.
     */
    val IS_USED: TableField<UsersPromocodesRecord, Boolean?> = createField(DSL.name("is_used"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<UsersPromocodesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UsersPromocodesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.users_promocodes</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.users_promocodes</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.users_promocodes</code> table reference
     */
    constructor(): this(DSL.name("users_promocodes"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UsersPromocodesRecord>): this(Internal.createPathAlias(child, key), child, key, USERS_PROMOCODES, null)
    public override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    public override fun getReferences(): List<ForeignKey<UsersPromocodesRecord, *>> = listOf(USERS_PROMOCODES__FK_USER_PROMOCODE, USERS_PROMOCODES__FK_PROMOCODE_USER)

    private lateinit var _users: Users
    private lateinit var _promocodes: Promocodes

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): Users {
        if (!this::_users.isInitialized)
            _users = Users(this, USERS_PROMOCODES__FK_USER_PROMOCODE)

        return _users;
    }

    val users: Users
        get(): Users = users()

    /**
     * Get the implicit join path to the <code>public.promocodes</code> table.
     */
    fun promocodes(): Promocodes {
        if (!this::_promocodes.isInitialized)
            _promocodes = Promocodes(this, USERS_PROMOCODES__FK_PROMOCODE_USER)

        return _promocodes;
    }

    val promocodes: Promocodes
        get(): Promocodes = promocodes()
    public override fun `as`(alias: String): UsersPromocodes = UsersPromocodes(DSL.name(alias), this)
    public override fun `as`(alias: Name): UsersPromocodes = UsersPromocodes(alias, this)
    public override fun `as`(alias: Table<*>): UsersPromocodes = UsersPromocodes(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    public override fun rename(name: String): UsersPromocodes = UsersPromocodes(DSL.name(name), null)

    /**
     * Rename this table
     */
    public override fun rename(name: Name): UsersPromocodes = UsersPromocodes(name, null)

    /**
     * Rename this table
     */
    public override fun rename(name: Table<*>): UsersPromocodes = UsersPromocodes(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    public override fun fieldsRow(): Row3<UUID?, UUID?, Boolean?> = super.fieldsRow() as Row3<UUID?, UUID?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, UUID?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, UUID?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
