/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db.tables.pojos


import java.io.Serializable
import java.time.LocalDate
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Promocodes(
    var uuid: UUID? = null,
    var name: String? = null,
    var description: String? = null,
    var value: String? = null,
    var generalCount: Int? = null,
    var availableCount: Int? = null,
    var expirationDate: LocalDate? = null,
    var cost: Int? = null,
    var avatarUrl: String? = null
): Serializable {


    public override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Promocodes = other as Promocodes
        if (this.uuid == null) {
            if (o.uuid != null)
                return false
        }
        else if (this.uuid != o.uuid)
            return false
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        if (this.description == null) {
            if (o.description != null)
                return false
        }
        else if (this.description != o.description)
            return false
        if (this.value == null) {
            if (o.value != null)
                return false
        }
        else if (this.value != o.value)
            return false
        if (this.generalCount == null) {
            if (o.generalCount != null)
                return false
        }
        else if (this.generalCount != o.generalCount)
            return false
        if (this.availableCount == null) {
            if (o.availableCount != null)
                return false
        }
        else if (this.availableCount != o.availableCount)
            return false
        if (this.expirationDate == null) {
            if (o.expirationDate != null)
                return false
        }
        else if (this.expirationDate != o.expirationDate)
            return false
        if (this.cost == null) {
            if (o.cost != null)
                return false
        }
        else if (this.cost != o.cost)
            return false
        if (this.avatarUrl == null) {
            if (o.avatarUrl != null)
                return false
        }
        else if (this.avatarUrl != o.avatarUrl)
            return false
        return true
    }

    public override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.uuid == null) 0 else this.uuid.hashCode())
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        result = prime * result + (if (this.description == null) 0 else this.description.hashCode())
        result = prime * result + (if (this.value == null) 0 else this.value.hashCode())
        result = prime * result + (if (this.generalCount == null) 0 else this.generalCount.hashCode())
        result = prime * result + (if (this.availableCount == null) 0 else this.availableCount.hashCode())
        result = prime * result + (if (this.expirationDate == null) 0 else this.expirationDate.hashCode())
        result = prime * result + (if (this.cost == null) 0 else this.cost.hashCode())
        result = prime * result + (if (this.avatarUrl == null) 0 else this.avatarUrl.hashCode())
        return result
    }

    public override fun toString(): String {
        val sb = StringBuilder("Promocodes (")

        sb.append(uuid)
        sb.append(", ").append(name)
        sb.append(", ").append(description)
        sb.append(", ").append(value)
        sb.append(", ").append(generalCount)
        sb.append(", ").append(availableCount)
        sb.append(", ").append(expirationDate)
        sb.append(", ").append(cost)
        sb.append(", ").append(avatarUrl)

        sb.append(")")
        return sb.toString()
    }
}
