/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class StepsChanges(
    var userUuid: UUID? = null,
    var diff: Int? = null,
    var timestamp: LocalDateTime? = null
): Serializable {


    public override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: StepsChanges = other as StepsChanges
        if (this.userUuid == null) {
            if (o.userUuid != null)
                return false
        }
        else if (this.userUuid != o.userUuid)
            return false
        if (this.diff == null) {
            if (o.diff != null)
                return false
        }
        else if (this.diff != o.diff)
            return false
        if (this.timestamp == null) {
            if (o.timestamp != null)
                return false
        }
        else if (this.timestamp != o.timestamp)
            return false
        return true
    }

    public override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.userUuid == null) 0 else this.userUuid.hashCode())
        result = prime * result + (if (this.diff == null) 0 else this.diff.hashCode())
        result = prime * result + (if (this.timestamp == null) 0 else this.timestamp.hashCode())
        return result
    }

    public override fun toString(): String {
        val sb = StringBuilder("StepsChanges (")

        sb.append(userUuid)
        sb.append(", ").append(diff)
        sb.append(", ").append(timestamp)

        sb.append(")")
        return sb.toString()
    }
}
