/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db.tables.pojos


import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UsersPromocodes(
    var userUuid: UUID? = null,
    var promocodeUuid: UUID? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsUsed")
    var isUsed: Boolean? = null
): Serializable {


    public override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UsersPromocodes = other as UsersPromocodes
        if (this.userUuid == null) {
            if (o.userUuid != null)
                return false
        }
        else if (this.userUuid != o.userUuid)
            return false
        if (this.promocodeUuid == null) {
            if (o.promocodeUuid != null)
                return false
        }
        else if (this.promocodeUuid != o.promocodeUuid)
            return false
        if (this.isUsed == null) {
            if (o.isUsed != null)
                return false
        }
        else if (this.isUsed != o.isUsed)
            return false
        return true
    }

    public override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.userUuid == null) 0 else this.userUuid.hashCode())
        result = prime * result + (if (this.promocodeUuid == null) 0 else this.promocodeUuid.hashCode())
        result = prime * result + (if (this.isUsed == null) 0 else this.isUsed.hashCode())
        return result
    }

    public override fun toString(): String {
        val sb = StringBuilder("UsersPromocodes (")

        sb.append(userUuid)
        sb.append(", ").append(promocodeUuid)
        sb.append(", ").append(isUsed)

        sb.append(")")
        return sb.toString()
    }
}
