/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db.tables.references


import org.kimp.earnactive.db.tables.Users



/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
