/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl
import org.kimp.earnactive.db.tables.Users


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.users</code>.
     */
    val USERS: Users get() = Users.USERS

    public override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    public override fun getTables(): List<Table<*>> = listOf(
        Users.USERS
    )
}
