/*
 * This file is generated by jOOQ.
 */
package org.kimp.earnactive.db.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.kimp.earnactive.db.tables.Users
import org.kimp.earnactive.db.tables.records.UsersRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val USERS_PHONE_KEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_phone_key"), arrayOf(Users.USERS.PHONE), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("USERS_pkey"), arrayOf(Users.USERS.UUID), true)
